/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package the.master.board;

import java.lang.reflect.Array;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Du
 */
public class Wind extends javax.swing.JFrame {

    public static final boolean INICIAR = false;
    public static Personagem[] lista = new Personagem[500];
    public static int counter = 0;

    /**
     * Creates new form Wind
     */
    public Wind() {
        // lista[0] = new Personagem("Novo Personagem", "Nova Classe");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        classe = new javax.swing.JComboBox();
        personagem = new javax.swing.JComboBox();
        addPersonagem = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        quantIntDis = new javax.swing.JSpinner();
        quantForDis = new javax.swing.JSpinner();
        quantVitDis = new javax.swing.JSpinner();
        quantSabDis = new javax.swing.JSpinner();
        quantCarDis = new javax.swing.JSpinner();
        quantSorDis = new javax.swing.JSpinner();
        quantHabDis = new javax.swing.JSpinner();
        quantAgiDis = new javax.swing.JSpinner();
        addAlma = new javax.swing.JButton();
        totalForDis = new javax.swing.JTextField();
        totalIntDis = new javax.swing.JTextField();
        totalSabDis = new javax.swing.JTextField();
        totalCarDis = new javax.swing.JTextField();
        totalVitDis = new javax.swing.JTextField();
        totalSorDis = new javax.swing.JTextField();
        totalAgiDis = new javax.swing.JTextField();
        totalHabDis = new javax.swing.JTextField();
        hpAtual = new javax.swing.JTextField();
        SpAtual = new javax.swing.JTextField();
        maoDirDis = new javax.swing.JComboBox();
        maoEsqDis = new javax.swing.JComboBox();
        armaduraDis = new javax.swing.JComboBox();
        acc1Dis = new javax.swing.JComboBox();
        acc2Dis = new javax.swing.JComboBox();
        acc3Dis = new javax.swing.JComboBox();
        habDis = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        habsCTDis = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textoDis = new javax.swing.JTextArea();
        salvaTexto = new javax.swing.JButton();
        HpMax = new javax.swing.JTextField();
        SpMax = new javax.swing.JTextField();
        novoNome = new javax.swing.JTextField();
        revestimentoMão1 = new javax.swing.JComboBox();
        revestimentoArmadura = new javax.swing.JComboBox();
        revestimentoMao2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        qntLvl = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        dado1 = new javax.swing.JTextField();
        acao = new javax.swing.JComboBox<>();
        resultadoBatalha = new javax.swing.JTextField();
        personagemAlvo = new javax.swing.JComboBox();
        dado2 = new javax.swing.JTextField();
        calcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setName("The Master Board"); // NOI18N

        classe.setEditable(true);
        classe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nova Classe", "Defender", "Violator Defender", "Nightmare Rider", "Unpurified Nightmare Rider", "Valkyrie", "Corrupted Valkyrie", "Druid", "Destructive Druid", "Shadowalker", "Sealed Shadowalker", "Berserker", "Unchained Berserker", "Trickster", "Ultimate Trickster", "Samurai", "Renegade Samurai", "Tamer", "Invincible Tamer", "Soulord", "Cursed Soulord", "Eagleborn", "Perfect Eagleborn", "Gambler", "Invict Gambler", "Dragon Knight", "Legendary Dragon Knight", "Musician", "Holy Musician", "Falconborn", "Archfalconborn", "Winterbringer", "Immortal Winterbringer" }));

        personagem.setEditable(true);
        personagem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Novo Personagem" }));
        personagem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        personagem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                personagemItemStateChanged(evt);
            }
        });
        personagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personagemActionPerformed(evt);
            }
        });
        for(int i = 0;lista[i] != null; i++){
            System.out.println(lista[i].getNome());
            if(lista[i] != null)
            personagem.insertItemAt(lista[i].getNome(), i);
            counter++;
        }

        addPersonagem.setText("ADD");
        addPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersonagemActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("For");

        jTextField2.setEditable(false);
        jTextField2.setText("Int");

        jTextField3.setEditable(false);
        jTextField3.setText("Vit");

        jTextField4.setEditable(false);
        jTextField4.setText("Sab");

        jTextField5.setEditable(false);
        jTextField5.setText("Car");

        jTextField6.setEditable(false);
        jTextField6.setText("Sor");

        jTextField7.setEditable(false);
        jTextField7.setText("Agi");

        jTextField8.setEditable(false);
        jTextField8.setText("Hab");

        addAlma.setText("Alma");
        addAlma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAlmaActionPerformed(evt);
            }
        });

        totalForDis.setEditable(false);
        totalForDis.setText("For");

        totalIntDis.setEditable(false);
        totalIntDis.setText("Int");

        totalSabDis.setEditable(false);
        totalSabDis.setText("Sab");

        totalCarDis.setEditable(false);
        totalCarDis.setText("Car");

        totalVitDis.setEditable(false);
        totalVitDis.setText("Vit");

        totalSorDis.setEditable(false);
        totalSorDis.setText("Sor");

        totalAgiDis.setEditable(false);
        totalAgiDis.setText("Agi");

        totalHabDis.setEditable(false);
        totalHabDis.setText("Hab");

        hpAtual.setText("HPAtual");
        hpAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpAtualActionPerformed(evt);
            }
        });

        SpAtual.setText("SpAtual");

        maoDirDis.setEditable(true);
        maoDirDis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mão Direita" }));
        maoDirDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maoDirDisActionPerformed(evt);
            }
        });

        maoEsqDis.setEditable(true);
        maoEsqDis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mão Esquerda" }));

        armaduraDis.setEditable(true);
        armaduraDis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Armadura" }));
        armaduraDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                armaduraDisActionPerformed(evt);
            }
        });

        acc1Dis.setEditable(true);
        acc1Dis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Acessório" }));

        acc2Dis.setEditable(true);
        acc2Dis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Acessório" }));

        acc3Dis.setEditable(true);
        acc3Dis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Acessório" }));

        habDis.setEditable(true);
        habDis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lâmina Estilhaçante", "Força Defensora", "Cura", "Luz", "Armadura de Vida Maldita", "Armadura de Espírito Maldita", "Nightmare", "Roleta da Morte", "Proteção", "Escudo/Espada Plasma", "Asas Astrais", "Cultivar Plantas", "Controle Espiritual", "Renovação de Espírito", "Espada de Vento", "Escuridão", "Roubar Alma", "Clones Sombrios", "Punhos de Tigre", "Uivo à Lua", "Frenesi", "Armadura de Ataque", "Retorno", "Prestidigitação", "Magia", "Enduir", "Bainha Espiritual", "Bainha Crescente", "Lâmina Contaminada", "Zanmato", "Invocar Kekoio", "Pétalas Explosivas", "Chicote de Espinhos", "Troca de Vida", "Materialização", "Imunidade", "Ingerir Almas", "Disparar Almas", "Penas Habilidades", "Garras Sanguinárias", "Guincho", "Ativar Moedas", "Dado de 6", "Dado Penal", "Perícia Com Bastão", "Alma do Dragão Azul", "Alma do Dragão Verde", "Alma do Dragão Amarelo", "Alma do Deus Da Música", "Melodia da Deusa do Triunfo", "Sinfonia do Deus do Ar", "Canto de Hioleteru", "Regenaração Final", "Agilidade Mística", "Refletir Status", "Silenciador Astral", "Hit Adcional", "Sangue Envenenado", "Reversão", "Troca Rápida", "Mira Perfeita", "Proteção Espectral", "Retalhação", "Corte Temporal", "Visão Arqueira", "Crítico", "Falcão", "Camuflagem", "Ventos do Inverno", "Aura Negra", "Sobrevivência", "Sopro Coronário" }));
        habDis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                habDisItemStateChanged(evt);
            }
        });
        habDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habDisActionPerformed(evt);
            }
        });

        habsCTDis.setEditable(false);
        habsCTDis.setColumns(20);
        habsCTDis.setRows(5);
        habsCTDis.setToolTipText("Descrição");
        jScrollPane1.setViewportView(habsCTDis);

        jLabel2.setText("Equipamentos");

        textoDis.setColumns(20);
        textoDis.setRows(5);
        textoDis.setToolTipText("Anotações");
        jScrollPane4.setViewportView(textoDis);

        salvaTexto.setText("Salvar");
        salvaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaTextoActionPerformed(evt);
            }
        });

        HpMax.setText("HpMax");
        HpMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HpMaxActionPerformed(evt);
            }
        });

        SpMax.setText("SpMax");

        novoNome.setText("Nome");

        revestimentoMão1.setEditable(true);
        revestimentoMão1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Revestimento" }));

        revestimentoArmadura.setEditable(true);
        revestimentoArmadura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Revestimento" }));

        revestimentoMao2.setEditable(true);
        revestimentoMao2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Revestimento" }));

        jLabel1.setText("HpAtual");

        jLabel3.setText("HpMax");

        jLabel4.setText("SpAtual");

        jLabel5.setText("SpMax");

        jLabel6.setText("Notas");

        jButton1.setText("Lista");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Nível");

        dado1.setText("Dado1");
        dado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dado1ActionPerformed(evt);
            }
        });

        acao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MiraVsEvasiva", "AtaqueVsDefesa", "MagiaVsDefesa", "AtaqueFurtivo", " ", " " }));
        acao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaoActionPerformed(evt);
            }
        });

        resultadoBatalha.setText("Valor");

        personagemAlvo.setEditable(true);
        personagemAlvo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Novo Personagem" }));
        personagemAlvo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        personagemAlvo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                personagemAlvoItemStateChanged(evt);
            }
        });
        personagemAlvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personagemAlvoActionPerformed(evt);
            }
        });
        for(int i = 0;lista[i] != null; i++){
            System.out.println(lista[i].getNome());
            if(lista[i] != null)
            personagemAlvo.insertItemAt(lista[i].getNome(), i);
        }

        dado2.setText("Dado2");

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personagem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(classe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(quantVitDis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(totalVitDis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(quantForDis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(totalForDis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(quantHabDis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(totalHabDis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(quantIntDis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(totalIntDis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(quantAgiDis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(totalAgiDis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(quantCarDis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(totalCarDis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(quantSabDis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(totalSabDis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(quantSorDis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(totalSorDis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(hpAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(HpMax, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SpAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SpMax, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(6, 7, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(novoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(resultadoBatalha, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(calcular)
                                            .addComponent(personagemAlvo, 0, 164, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(dado1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(dado2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(acao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(maoDirDis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(47, 47, 47)))
                                            .addComponent(revestimentoMão1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(maoEsqDis, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(armaduraDis, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(acc1Dis, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(revestimentoMao2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(revestimentoArmadura, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(acc2Dis, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(acc3Dis, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(qntLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(salvaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(190, 190, 190)
                                        .addComponent(addAlma, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(14, 14, 14)
                                        .addComponent(addPersonagem)))
                                .addContainerGap(20, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(habDis, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(novoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qntLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPersonagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addAlma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hpAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HpMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantForDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalForDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantIntDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalIntDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(quantVitDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(totalVitDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(quantSabDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(totalSabDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(quantCarDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(totalCarDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantSorDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalSorDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantAgiDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalAgiDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantHabDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalHabDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(acao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(personagemAlvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(calcular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultadoBatalha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(salvaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maoDirDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(revestimentoMão1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maoEsqDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(revestimentoMao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(armaduraDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(revestimentoArmadura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(acc1Dis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(acc2Dis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(acc3Dis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(habDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvaTextoActionPerformed
        int i = getCurrentPersonagemId(lista, personagem.getSelectedItem().toString());
        if (i != -1) {

            //atualizaçoes e updates no banco
            lista[i].setCondBox(textoDis.getText());
            lista[i].setLvl((int) qntLvl.getValue());
            lista[i].setQuantFor((int) quantForDis.getValue());
            lista[i].setQuantInt((int) quantIntDis.getValue());
            lista[i].setQuantVit((int) quantVitDis.getValue());
            lista[i].setQuantSab((int) quantSabDis.getValue());
            lista[i].setQuantCar((int) quantCarDis.getValue());
            lista[i].setQuantSor((int) quantSorDis.getValue());
            lista[i].setQuantAgi((int) quantAgiDis.getValue());
            lista[i].setQuantHab((int) quantHabDis.getValue());
            lista[i].setHpAtual(Integer.parseInt(hpAtual.getText()));
            lista[i].setHpMax(Integer.parseInt(HpMax.getText()));
            lista[i].setSpAtual(Integer.parseInt(SpAtual.getText()));
            lista[i].setSpMax(Integer.parseInt(SpMax.getText()));

            String query = "UPDATE personagem SET condBox = '" + lista[i].getCondBox().replace("'", " ").replace("\"", " ") + "', lvl = " + lista[i].getLvl() + ", quantFor = " + lista[i].getQuantFor() + ", quantInt = " + lista[i].getQuantInt() + ", quantVit = " + lista[i].getQuantVit() + ", quantSab = " + lista[i].getQuantSab() + ", quantCar = " + lista[i].getQuantCar() + ", quantSor = " + lista[i].getQuantSor() + ", quantAgi = " + lista[i].getQuantAgi() + ", quantHab = " + lista[i].getQuantHab() + ", hpMax = " + lista[i].getHpMax() + ", hpAtual = " + lista[i].getHpAtual() + ", spMax = " + lista[i].getSpMax() + ", spAtual = " + lista[i].getSpAtual() + " WHERE nome = '" + lista[i].getNome() + "';";
            Database.atualizar(query);
            lista = Database.recuperarPersonagens(lista);

            if (personagem.getSelectedItem().toString().equals("Novo Personagem")) {
            } else {
                if (personagem.getSelectedItem().toString().equals(lista[i].getNome())) {
                    classe.setSelectedItem(lista[i].getClasse());
                    qntLvl.setValue(lista[i].getLvl());
                    textoDis.setText(lista[i].getCondBox());
                    quantForDis.setValue(lista[i].getQuantFor());
                    quantIntDis.setValue(lista[i].getQuantInt());
                    quantSabDis.setValue(lista[i].getQuantSab());
                    quantVitDis.setValue(lista[i].getQuantVit());
                    quantCarDis.setValue(lista[i].getQuantCar());
                    quantSorDis.setValue(lista[i].getQuantSor());
                    quantAgiDis.setValue(lista[i].getQuantAgi());
                    quantHabDis.setValue(lista[i].getQuantHab());
                    HpMax.setText(Integer.toString(lista[i].getHpMax()));
                    hpAtual.setText(Integer.toString(lista[i].getHpAtual()));
                    SpMax.setText(Integer.toString(lista[i].getSpMax()));
                    SpAtual.setText(Integer.toString(lista[i].getSpAtual()));
                }
            }
            //textoDis.setText(lista[getCurrentPersonagemId(lista, personagem.getSelectedItem().toString())].getCondBox());

        }
    }//GEN-LAST:event_salvaTextoActionPerformed

    private void habDisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_habDisItemStateChanged
        habsCTDis.setText(Habilidade.returnDesc(habDis.getSelectedItem().toString()));

    }//GEN-LAST:event_habDisItemStateChanged

    private void armaduraDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_armaduraDisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_armaduraDisActionPerformed

    private void maoDirDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maoDirDisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maoDirDisActionPerformed

    private void addPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersonagemActionPerformed
        /*for(int i = 0; i < counter; i++)
        personagem.insertItemAt(lista[i].getNome(), 0);*/

        boolean existe = false;

        if (classe.getSelectedIndex() != 0) {
            for (int i = 0; i < personagem.getItemCount(); i++) {
                if (personagem.getItemAt(i).toString().equals(novoNome.getText())) {
                    existe = true;
                }
            }
            if (existe == false) {
                personagem.insertItemAt(novoNome.getText(), 0);
                //personagemAlvo.insertItemAt(novoNome.getText(), 0);
                lista[counter] = new Personagem(novoNome.getText(), classe.getSelectedItem().toString());
                counter++;
            } else {
                JOptionPane.showMessageDialog( // Caixa de mensagem
                        this, // Janela da aplicação (opcional, pode ser null)
                        "Esse personagem já existe!", // Mensagem
                        "Erro!", // Título da caixa de mensagem
                        JOptionPane.ERROR_MESSAGE // Ícone da caixa de mensagem
                );;
            }
        } else {
            JOptionPane.showMessageDialog( // Caixa de mensagem
                    this, // Janela da aplicação (opcional, pode ser null)
                    "Escolha uma Classe!", // Mensagem
                    "Erro!", // Título da caixa de mensagem
                    JOptionPane.ERROR_MESSAGE // Ícone da caixa de mensagem
            );
        }

    }//GEN-LAST:event_addPersonagemActionPerformed

    private void personagemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_personagemItemStateChanged
        for (int i = 0; i < personagem.getItemCount(); i++) {
            if (personagem.getSelectedItem().toString().equals("Novo Personagem")) {
                classe.setSelectedItem("Nova Classe");
                return;
            } else {
                if (personagem.getSelectedItem().toString().equals(lista[i].getNome())) {
                    classe.setSelectedItem(lista[i].getClasse());
                    qntLvl.setValue(lista[i].getLvl());
                    textoDis.setText(lista[i].getCondBox());
                    quantForDis.setValue(lista[i].getQuantFor());
                    quantIntDis.setValue(lista[i].getQuantInt());
                    quantSabDis.setValue(lista[i].getQuantSab());
                    quantVitDis.setValue(lista[i].getQuantVit());
                    quantCarDis.setValue(lista[i].getQuantCar());
                    quantSorDis.setValue(lista[i].getQuantSor());
                    quantAgiDis.setValue(lista[i].getQuantAgi());
                    quantHabDis.setValue(lista[i].getQuantHab());
                    HpMax.setText(Integer.toString(lista[i].getHpMax()));
                    hpAtual.setText(Integer.toString(lista[i].getHpAtual()));
                    SpMax.setText(Integer.toString(lista[i].getSpMax()));
                    SpAtual.setText(Integer.toString(lista[i].getSpAtual()));

                    //textoDis.setText(lista[getCurrentPersonagemId(lista, personagem.getSelectedItem().toString())].getCondBox());
                    return;
                }
            }
        }
    }//GEN-LAST:event_personagemItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (classe.getSelectedIndex() != 0) {
            Database.atualizar("CREATE OR REPLACE VIEW PersonagensPorClasse(nome) as"
                    + " (SELECT Personagem.nome FROM Personagem WHERE Personagem.classe = '" + classe.getSelectedItem().toString() + "');");
            JOptionPane.showMessageDialog( // Caixa de mensagem
                    this, // Janela da aplicação (opcional, pode ser null)   
                    Database.recuperarInfo("nome", "SELECT nome FROM PersonagensPorClasse;"), // Mensagem
                    classe.getSelectedItem().toString(), // Título da caixa de mensagem
                    JOptionPane.INFORMATION_MESSAGE // Ícone da caixa de mensagem
            );

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hpAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hpAtualActionPerformed

    private void HpMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HpMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HpMaxActionPerformed

    private void personagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personagemActionPerformed

    private void acaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acaoActionPerformed

    private void habDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habDisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_habDisActionPerformed

    private void personagemAlvoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_personagemAlvoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_personagemAlvoItemStateChanged

    private void personagemAlvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personagemAlvoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personagemAlvoActionPerformed

    private void dado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dado1ActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:
        resultadoBatalha.setText((Float.toString(Database.recuperarFunc(acao.getSelectedItem().toString(), personagem.getSelectedItem().toString(), Integer.parseInt(dado1.getText()), personagemAlvo.getSelectedItem().toString(), Integer.parseInt(dado2.getText())))));
    }//GEN-LAST:event_calcularActionPerformed

    private void addAlmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAlmaActionPerformed
         if (classe.getSelectedIndex() != 0) {
            Database.atualizar("CREATE OR REPLACE VIEW AlmaPersonagem(nome, bonfor, bonint, bonvit, bonsab, boncar, bonagi, bonsor, bonhab) as"
                    + " (SELECT nome, bonfor, bonint, bonvit, bonsab, boncar, bonagi, bonsor, bonhab FROM Alma WHERE Alma.nome = '" + personagem.getSelectedItem().toString() + "');");
            JOptionPane.showMessageDialog( // Caixa de mensagem
                    this, // Janela da aplicação (opcional, pode ser null)   
                    Database.recuperarInfoAlma("SELECT nome, bonfor, bonint, bonvit, bonsab, boncar, bonagi, bonsor, bonhab FROM AlmaPersonagem as tabem;"), // Mensagem
                    classe.getSelectedItem().toString(), // Título da caixa de mensagem
                    JOptionPane.INFORMATION_MESSAGE // Ícone da caixa de mensagem
            );

        }
    }//GEN-LAST:event_addAlmaActionPerformed

    private int getCurrentPersonagemId(Personagem[] listax, String nome) {
        for (int i = 0; listax[i] != null; i++) {
            if (listax[i].getNome().equals(nome)) {
                return i;
            }
        }
        System.out.println("Erro getCurrent");
        return -1;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (INICIAR) {
                    //Database.atualizar("CREATE DATABASE if not exists test;");
                    Database.atualizar(Classe.criarTabela());
                    Database.atualizar(Equipamento.criarTabela());
                    Database.atualizar(Habilidade.criarTabela());
                    Database.atualizar(Personagem.criarTabela());
                    Database.atualizar(Alma.criarTabela());
                    Habilidade.habInit();
                    Equipamento.equipInit();
                    Classe.classesInit();
                };
                //Habilidade.habInit();
                //Equipamento.equipInit();
                //Classe.classesInit();
                lista = Database.recuperarPersonagens(lista);

                new Wind().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HpMax;
    private javax.swing.JTextField SpAtual;
    private javax.swing.JTextField SpMax;
    private javax.swing.JComboBox<String> acao;
    private javax.swing.JComboBox acc1Dis;
    private javax.swing.JComboBox acc2Dis;
    private javax.swing.JComboBox acc3Dis;
    private javax.swing.JButton addAlma;
    private javax.swing.JButton addPersonagem;
    private javax.swing.JComboBox armaduraDis;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calcular;
    private javax.swing.JComboBox classe;
    private javax.swing.JTextField dado1;
    private javax.swing.JTextField dado2;
    private javax.swing.JComboBox habDis;
    private javax.swing.JTextArea habsCTDis;
    private javax.swing.JTextField hpAtual;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JComboBox maoDirDis;
    private javax.swing.JComboBox maoEsqDis;
    private javax.swing.JTextField novoNome;
    public static javax.swing.JComboBox personagem;
    public static javax.swing.JComboBox personagemAlvo;
    private javax.swing.JSpinner qntLvl;
    private javax.swing.JSpinner quantAgiDis;
    private javax.swing.JSpinner quantCarDis;
    private javax.swing.JSpinner quantForDis;
    private javax.swing.JSpinner quantHabDis;
    private javax.swing.JSpinner quantIntDis;
    private javax.swing.JSpinner quantSabDis;
    private javax.swing.JSpinner quantSorDis;
    private javax.swing.JSpinner quantVitDis;
    private javax.swing.JTextField resultadoBatalha;
    private javax.swing.JComboBox revestimentoArmadura;
    private javax.swing.JComboBox revestimentoMao2;
    private javax.swing.JComboBox revestimentoMão1;
    private javax.swing.JButton salvaTexto;
    private javax.swing.JTextArea textoDis;
    private javax.swing.JTextField totalAgiDis;
    private javax.swing.JTextField totalCarDis;
    private javax.swing.JTextField totalForDis;
    private javax.swing.JTextField totalHabDis;
    private javax.swing.JTextField totalIntDis;
    private javax.swing.JTextField totalSabDis;
    private javax.swing.JTextField totalSorDis;
    private javax.swing.JTextField totalVitDis;
    // End of variables declaration//GEN-END:variables
}
